### ISSUE TITLE
Illegal export declaration and illegal import declaration

### ISSUE THREAD

**Issue by skchen28** [sayll/ie-webpack-start#24]
相关包有redux-thunk依赖，然后报如下错误：

> 
ERROR in ./~/redux-thunk/es/index.js
Module build failed: Error: Parse Error: Line 18: Illegal export declaration
    at throwError (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:2823:21)
    at throwErrorTolerant (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:2835:24)
    at parseSourceElement (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:6432:17)
    at parseProgramElement (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:6491:16)
    at parseProgramElements (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:6523:29)
    at parseProgram (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:6536:16)
    at Object.parse (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:7713:23)
    at getAstForSource (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\jstransform\src\jstransform.js:244:21)
    at Object.transform (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\jstransform\src\jstransform.js:267:11)
    at transform (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\es3ify\index.js:108:24)
    at Object.module.exports (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\es3ify-loader\index.js:5:10)
 @ ./~/react-form/es/components/Form.js 25:18-40

ERROR in ./~/redux/es/index.js
Module build failed: Error: Parse Error: Line 1: Illegal import declaration
    at throwError (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:2823:21)
    at throwErrorTolerant (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:2835:24)
    at parseSourceElement (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:6435:17)
    at parseProgramElement (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:6491:16)
    at parseProgramElements (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:6523:29)
    at parseProgram (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:6536:16)
    at Object.parse (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\esprima-fb\esprima.js:7713:23)
    at getAstForSource (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\jstransform\src\jstransform.js:244:21)
    at Object.transform (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\jstransform\src\jstransform.js:267:11)
    at transform (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\es3ify\index.js:108:24)
    at Object.module.exports (F:\Projects\com-work\education\edu-oxford\yey\oxford-yey-pc\node_modules\es3ify-loader\index.js:5:10)
 @ ./~/react-form/es/components/Form.js 29:13-29
 @ ./~/react-form/es/index.js
 @ ./src/view/applicationNotes/applicationNotes.js
 @ multi webpack-hot-middleware/client?reload=true ./src/view/applicationNotes/applicationNotes.js
>

**Comment by sayll** [comment]
react用户，不建议使用这个版本的脚手架，不过，近期也有计划对这个脚手架全面进行更新。

**Comment by skchen28** [comment]
那react支持IE8有啥好的建议吗
